// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"iphonectl-pp-cli/internal/cli"
	"iphonectl-pp-cli/internal/client"
	"iphonectl-pp-cli/internal/cliutil"
	"iphonectl-pp-cli/internal/config"
	"iphonectl-pp-cli/internal/learn"
	"iphonectl-pp-cli/internal/mcp/bound"
	"iphonectl-pp-cli/internal/mcp/cobratree"
	"iphonectl-pp-cli/internal/platform"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	s.AddTool(
		mcplib.NewTool("screenshot_screenshot",
			mcplib.WithDescription("Full-screen PNG as base64 (session-less). Returns the Value."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/screenshot", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("session_create",
			mcplib.WithDescription("Create a WDA session (returns sessionId used by all action routes). Optional: capabilities."),
			mcplib.WithObject("capabilities", mcplib.Description("W3C capabilities; bundleId under alwaysMatch launches that app")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "capabilities", WireName: "capabilities", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("session_delete",
			mcplib.WithDescription("End a session. Required: sessionId. Destructive."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/session/{sessionId}", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_element_click",
			mcplib.WithDescription("Tap a previously found element by its element id. Required: sessionId, uuid."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("uuid", mcplib.Required(), mcplib.Description("element id returned by findElement")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/element/{uuid}/click", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "uuid", WireName: "uuid", Location: "path"}}, []string{"sessionId", "uuid"}),
	)
	s.AddTool(
		mcplib.NewTool("session_element_find",
			mcplib.WithDescription("Find one element by strategy + selector. Required: sessionId, using, value. Returns the new Value."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("using", mcplib.Required(), mcplib.Description("Using")),
			mcplib.WithString("value", mcplib.Required(), mcplib.Description("Value")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/element", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "using", WireName: "using", Location: "body"}, {PublicName: "value", WireName: "value", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_element_set-value",
			mcplib.WithDescription("Type text into a found element. Required: sessionId, uuid, value."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("uuid", mcplib.Required(), mcplib.Description("element id returned by findElement")),
			mcplib.WithString("value", mcplib.Required(), mcplib.Description("Value")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/element/{uuid}/value", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "uuid", WireName: "uuid", Location: "path"}, {PublicName: "value", WireName: "value", Location: "body"}}, []string{"sessionId", "uuid"}),
	)
	s.AddTool(
		mcplib.NewTool("session_element_text",
			mcplib.WithDescription("Read an element's text. Required: sessionId, uuid. Returns the Value."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("uuid", mcplib.Required(), mcplib.Description("element id returned by findElement")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/session/{sessionId}/element/{uuid}/text", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "uuid", WireName: "uuid", Location: "path"}}, []string{"sessionId", "uuid"}),
	)
	s.AddTool(
		mcplib.NewTool("session_url_open",
			mcplib.WithDescription("Open a URL/deep-link in the foreground app. Required: sessionId, url."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("url", mcplib.Required(), mcplib.Description("Url")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/url", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "url", WireName: "url", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_activate-app",
			mcplib.WithDescription("Bring a background app to the foreground by bundle id. Required: sessionId, bundleId."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("bundleId", mcplib.Required(), mcplib.Description("Bundle id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/apps/activate", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "bundleId", WireName: "bundleId", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_app-state",
			mcplib.WithDescription("Query an app's run state (0..4) by bundle id. Required: sessionId, bundleId. Returns the new Value."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("bundleId", mcplib.Required(), mcplib.Description("Bundle id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/apps/state", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "bundleId", WireName: "bundleId", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_double-tap",
			mcplib.WithDescription("Double-tap at coordinates. Required: sessionId, x, y."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithNumber("x", mcplib.Required(), mcplib.Description("absolute screen x in points")),
			mcplib.WithNumber("y", mcplib.Required(), mcplib.Description("absolute screen y in points")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/doubleTap", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "x", WireName: "x", Location: "body"}, {PublicName: "y", WireName: "y", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_drag",
			mcplib.WithDescription("Drag from one coordinate to another over a duration. Required: sessionId, duration, fromX, fromY, toX, toY."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithNumber("duration", mcplib.Required(), mcplib.Description("seconds")),
			mcplib.WithNumber("fromX", mcplib.Required(), mcplib.Description("From x")),
			mcplib.WithNumber("fromY", mcplib.Required(), mcplib.Description("From y")),
			mcplib.WithNumber("toX", mcplib.Required(), mcplib.Description("To x")),
			mcplib.WithNumber("toY", mcplib.Required(), mcplib.Description("To y")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/dragfromtoforduration", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "duration", WireName: "duration", Location: "body"}, {PublicName: "fromX", WireName: "fromX", Location: "body"}, {PublicName: "fromY", WireName: "fromY", Location: "body"}, {PublicName: "toX", WireName: "toX", Location: "body"}, {PublicName: "toY", WireName: "toY", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_launch-app",
			mcplib.WithDescription("Launch (or foreground) an app by bundle id. Required: sessionId, bundleId."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("bundleId", mcplib.Required(), mcplib.Description("Bundle id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/apps/launch", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "bundleId", WireName: "bundleId", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_press-button",
			mcplib.WithDescription("Press a hardware button (home, volumeUp, volumeDown). Required: sessionId, name."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/pressButton", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_send-keys",
			mcplib.WithDescription("Type text into the focused field. Required: sessionId, value."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("value", mcplib.Required(), mcplib.Description("characters/strings to type, e.g. ['hello']")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/keys", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "value", WireName: "value", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_siri",
			mcplib.WithDescription("Invoke Siri with a spoken text command. Required: sessionId, text."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/siri/activate", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "text", WireName: "text", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_swipe",
			mcplib.WithDescription("Directional swipe (up/down/left/right). Required: sessionId, direction."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("direction", mcplib.Required(), mcplib.Description("Direction")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/swipe", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "direction", WireName: "direction", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_tap",
			mcplib.WithDescription("Tap at absolute screen coordinates. Required: sessionId, x, y."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithNumber("x", mcplib.Required(), mcplib.Description("absolute screen x in points")),
			mcplib.WithNumber("y", mcplib.Required(), mcplib.Description("absolute screen y in points")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/tap", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "x", WireName: "x", Location: "body"}, {PublicName: "y", WireName: "y", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_terminate-app",
			mcplib.WithDescription("Terminate an app by bundle id. Required: sessionId, bundleId."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithString("bundleId", mcplib.Required(), mcplib.Description("Bundle id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/apps/terminate", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "bundleId", WireName: "bundleId", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("session_wda_touch-and-hold",
			mcplib.WithDescription("Long-press at coordinates for a duration. Required: sessionId, x, y. Optional: duration."),
			mcplib.WithString("sessionId", mcplib.Required(), mcplib.Description("id returned by POST /session")),
			mcplib.WithNumber("duration", mcplib.Description("seconds")),
			mcplib.WithNumber("x", mcplib.Required(), mcplib.Description("absolute screen x in points")),
			mcplib.WithNumber("y", mcplib.Required(), mcplib.Description("absolute screen y in points")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/session/{sessionId}/wda/touchAndHold", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sessionId", WireName: "sessionId", Location: "path"}, {PublicName: "duration", WireName: "duration", Location: "body"}, {PublicName: "x", WireName: "x", Location: "body"}, {PublicName: "y", WireName: "y", Location: "body"}}, []string{"sessionId"}),
	)
	s.AddTool(
		mcplib.NewTool("source_page",
			mcplib.WithDescription("UI hierarchy (accessibility tree) as XML or JSON. Optional: format (default: xml). Returns the Value."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/source", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", Default: "xml"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("status_get",
			mcplib.WithDescription("Server + device readiness (session-less; use for healthcheck). Returns the Value."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/status", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_active-app-info",
			mcplib.WithDescription("Bundle id + pid of the foreground app. Returns the Value."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/wda/activeAppInfo", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_battery-info",
			mcplib.WithDescription("Battery level and state. Returns the Value."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/wda/batteryInfo", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_device-info",
			mcplib.WithDescription("Device model, iOS version, screen size, etc. Returns the Value."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/wda/device/info", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_homescreen",
			mcplib.WithDescription("Press Home / go to the Home Screen (session-less)."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/wda/homescreen", false, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_is-locked",
			mcplib.WithDescription("Whether the screen is locked (session-less). Returns the Value."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/wda/locked", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_lock",
			mcplib.WithDescription("Lock the screen (session-less)."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/wda/lock", false, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wda_unlock",
			mcplib.WithDescription("Unlock the screen (session-less; phone must have no/known passcode)."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/wda/unlock", false, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	Default    string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'iphonectl-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'iphonectl-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	c := newMCPClientFromConfig(cfg)
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	return c, session, nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "iphonectl",
		"description": "REST control surface for an iOS device via WebDriverAgent (WDA)",
		"archetype":   "generic",
		"tool_count":  29,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion iphonectl-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"resources": []map[string]any{
			{
				"name":        "screenshot",
				"description": "Manage screenshot",
				"endpoints":   []string{"screenshot"},
			},
			{
				"name":        "session",
				"description": "Manage session",
				"endpoints":   []string{"create", "delete"},
				"writable":    true,
			},
			{
				"name":        "session.element",
				"description": "Manage element",
				"endpoints":   []string{"click", "find", "set-value", "text"},
				"writable":    true,
			},
			{
				"name":        "session.url",
				"description": "Manage url",
				"endpoints":   []string{"open"},
				"writable":    true,
			},
			{
				"name":        "session.wda",
				"description": "Manage wda",
				"endpoints":   []string{"activate-app", "app-state", "double-tap", "drag", "launch-app", "press-button", "send-keys", "siri", "swipe", "tap", "terminate-app", "touch-and-hold"},
				"writable":    true,
			},
			{
				"name":        "source",
				"description": "Manage source",
				"endpoints":   []string{"page"},
				"searchable":  true,
			},
			{
				"name":        "status",
				"description": "Manage status",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "wda",
				"description": "Manage wda",
				"endpoints":   []string{"active-app-info", "battery-info", "device-info", "homescreen", "is-locked", "lock", "unlock"},
				"searchable":  true,
				"writable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
