// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSourcePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagFormat string

	cmd := &cobra.Command{
		Use:         "source",
		Short:       "UI hierarchy (accessibility tree) as XML or JSON",
		Long:        "UI hierarchy (accessibility tree) as XML or JSON",
		Example:     "  iphonectl-pp-cli source",
		Annotations: map[string]string{"pp:endpoint": "source.page", "pp:method": "GET", "pp:path": "/source", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"xml", "json", "description"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagFormat, "format", allowedFormat)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/source"
			params := map[string]string{}
			if flagFormat != "" {
				params["format"] = formatCLIParamValue(flagFormat)
			}
			data, err := c.Get(cmd.Context(), path, params)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if isDryRunResponse(c.IsDryRun(), data) {
				if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
					return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "dry-run"})
				}
				return nil
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagFormat, "format", "xml", "Format (one of: xml, json, description)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
