// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSessionElementCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "element",
		Short:       "Get, find, and create element for session",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSessionElementClickCmd(flags))
	cmd.AddCommand(newSessionElementFindCmd(flags))
	cmd.AddCommand(newSessionElementSetValueCmd(flags))
	cmd.AddCommand(newSessionElementTextCmd(flags))
	return cmd
}
