// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSessionWdaCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "wda",
		Short:       "Create and send wda for session",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSessionWdaActivateAppCmd(flags))
	cmd.AddCommand(newSessionWdaAppStateCmd(flags))
	cmd.AddCommand(newSessionWdaDoubleTapCmd(flags))
	cmd.AddCommand(newSessionWdaDragCmd(flags))
	cmd.AddCommand(newSessionWdaLaunchAppCmd(flags))
	cmd.AddCommand(newSessionWdaPressButtonCmd(flags))
	cmd.AddCommand(newSessionWdaSendKeysCmd(flags))
	cmd.AddCommand(newSessionWdaSiriCmd(flags))
	cmd.AddCommand(newSessionWdaSwipeCmd(flags))
	cmd.AddCommand(newSessionWdaTapCmd(flags))
	cmd.AddCommand(newSessionWdaTerminateAppCmd(flags))
	cmd.AddCommand(newSessionWdaTouchAndHoldCmd(flags))
	return cmd
}
