// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSessionElementTextCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "text <sessionId> <uuid>",
		Aliases:     []string{"get"},
		Short:       "Read an element's text",
		Example:     "  iphonectl-pp-cli session element text 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "element.text", "pp:method": "GET", "pp:path": "/session/{sessionId}/element/{uuid}/text", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <sessionId> <uuid>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <sessionId> <uuid>"))
			}
			path := "/session/{sessionId}/element/{uuid}/text"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("sessionId is required\nUsage: %s <%s>", cmd.CommandPath(), "sessionId"))
			}
			path = replacePathParam(path, "sessionId", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("uuid is required\nUsage: %s <%s>", cmd.CommandPath(), "uuid"))
			}
			path = replacePathParam(path, "uuid", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			data, err := c.Get(cmd.Context(), path, params)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if isDryRunResponse(c.IsDryRun(), data) {
				if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
					return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "dry-run"})
				}
				return nil
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"})
		},
	}

	return cmd
}
