// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSessionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "session",
		Short:       "Create and delete session",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSessionCreateCmd(flags))
	cmd.AddCommand(newSessionDeleteCmd(flags))
	cmd.AddCommand(newSessionElementCmd(flags))
	cmd.AddCommand(newSessionUrlCmd(flags))
	cmd.AddCommand(newSessionWdaCmd(flags))
	return cmd
}
