// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWdaCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "wda",
		Short:       "Get and create wda",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWdaActiveAppInfoCmd(flags))
	cmd.AddCommand(newWdaBatteryInfoCmd(flags))
	cmd.AddCommand(newWdaDeviceInfoCmd(flags))
	cmd.AddCommand(newWdaHomescreenCmd(flags))
	cmd.AddCommand(newWdaIsLockedCmd(flags))
	cmd.AddCommand(newWdaLockCmd(flags))
	cmd.AddCommand(newWdaUnlockCmd(flags))
	return cmd
}
