// Copyright 2026 Barklees Sanders and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type BundleId struct {
	BundleId string `json:"bundleId"`
}

type CreateSessionBody struct {
	Capabilities json.RawMessage `json:"capabilities"`
}

type Locator struct {
	Using string `json:"using"`
	Value string `json:"value"`
}

type SessionValue struct {
	SessionId string          `json:"sessionId"`
	Value     json.RawMessage `json:"value"`
}

type Value struct {
	SessionId string `json:"sessionId"`
	Value     string `json:"value"`
}

type XY struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}
